### ISSUE TITLE
New side channel attack on Wi-Fi hardware AES encryption modules

### ISSUE THREAD

**Issue by klukonin** [greearb/ath10k-ct#27]
Here is the info about new attack
http://s3.eurecom.fr/tools/screaming_channels/
http://s3.eurecom.fr/docs/ccs18_camurati_preprint.pdf
https://github.com/eurecom-s3/screaming_channels#Story

Does CT firmware related to this attack and is there any chance to add extra interrupts with random operations  (or something else) during the encryption process to prevent the key leak ?

**Comment by greearb** [comment]
Based on my limited understanding, I would think that ath10k NICs could be susceptible since their hw crypt logic is near the RF logic on the NICs.  Software/firmware has no direct control over how/when the encryption happens.  I guess you might could eventually get cpu tx encryption working (I have rx cpu encryption working already), but it would be a lot of work and would kill performance.  Maybe ask on the ath10k mailing list and/or your NIC vendor...hardware folks and/or hackers like those that found this bug would be able to give you a better answer.

**Comment by klukonin** [comment]
Bad news. 
But, thank you very much for so detailed answer.
I'll ask ath10k mailing list, sure.
